[package]
name = "bnb-ast"
version = "0.1.0"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
serde = { version = "1", default-features = false, features = [
  "derive",
  "std",
] }
